# -*- coding: GBK -*-

DB_NAME = "UserData.db"

# message
MSG_SC_LOGIN_RESULT = 1001
MSG_CS_REGISTER = 2001
MSG_CS_LOGIN = 2002
MSG_CS_LOGOUT = 2003
MSG_CS_MATCH_REQUEST = 2004
MSG_CS_MATCH_CANCEL = 2005
MSG_SC_ROOMMATE_ADD = 1008
MSG_SC_ROOMMATE_DEL = 1009
MSG_SC_MAP_LOAD = 1010   # notify clients loading map.
MSG_SC_GAME_OBJECT_DIE = 1011
MSG_CS_LOAD_FINISHED = 2007  # client notify server load finished

# room & arena
MSG_SC_START_GAME = 1002

# player
MSG_SC_PLAYER_BORN = 1004
MSG_CS_PLAYER_MOVE = 2006
MSG_CS_PLAYER_ATTACK = 2222
MSG_CS_PLAYER_ATTACK_MOVE = 2223
MSG_CS_PLAYER_HIT = 2224
MSG_CS_PLAYER_ATTACK_HIT_EFFECT = 2225

MSG_SC_PLAYER_LEAVE = 2234

MSG_CS_PLAYER_COLLECT = 2225
MSG_SC_PLAYER_COLLECT = 2230

MSG_CS_PLAYER_REAP = 2226

MSG_SC_MAP_ITEM_DESTROY = 2229
MSG_SC_BACKPACK_SYN = 2232

'''
:describe: When the player install weapon and armor[cloth and hat] send this message to server.
'''
MSG_CS_PLAYER_DRESS = 2227

'''
:describe: broadcast player armor and weapon dress.
'''
MSG_CS_ARMOR_INSTALL = 4001
MSG_CS_WEAPON_INSTALL = 4002
MSG_CS_HAT_INSTALL = 4003

MSG_CS_WEAPON_UNINSTALL = 4005
MSG_SC_WEAPON_INSTALL = 4008
MSG_SC_WEAPON_UNINSTALL = 4011

MSG_CS_WEAPON_ACTIVE = 4012

MSG_CS_PLAYER_DROP = 4013

'''制作消息请求'''
MSG_CS_MAKE_REQUEST = 4014


MSG_CS_ALIVE = 3000

# entities
MSG_SC_ENTITY_BORN = 1005

# game
MSG_SC_GAME_WIN = 1006
MSG_SC_GAME_OVER = 1007

# service id
USER_SERVICES = 1
ARENA_SERVICES = 2

NET_STATE_STOP = 0				# state: init value
NET_STATE_CONNECTING = 1		# state: connecting
NET_STATE_ESTABLISHED = 2		# state: connected

NET_HEAD_LENGTH_SIZE = 4		# 4 bytes little endian (x86)
NET_HEAD_LENGTH_FORMAT = '<I'

NET_CONNECTION_NEW = 0  # new connection
NET_CONNECTION_LEAVE = 1  # lost connection
NET_CONNECTION_DATA = 2  # data comming

NET_HOST_DEFAULT_TIMEOUT = 70

MAX_HOST_CLIENTS_INDEX = 0xffff
MAX_HOST_CLIENTS_BYTES = 16

SERVER_IP = "127.0.0.1"
SERVER_PORT = 2000


